### PR TITLE
Add loops

### PR DESCRIPTION
**Pull request by varkor**
This adds support for loops, as seen below.

image

Multiple loops are permitted on an object.

image

This is facilitated by a new "add loop" button that appears on hover.

image

There is also the option to rotate the loop through 90°. The loop direction can also be reversed.

image

Resolves https://github.com/yishn/tikzcd-editor/issues/18.

---

I imagine there are probably some behaviours I've overlooked in the interaction with loops, so let me know if something doesn't seem natural, or doesn't work as expected.

### CODE REVIEW

**Comment by varkor** [comment]
Note that this depends on https://github.com/yishn/jsx-tikzcd/pull/5 to generate correct TikZ, so this will have to be updated before this is merged.

**Comment by yishn** [comment]
@varkor I've published a new version of jsx-tikzcd with your changes and updated the dependencies. Can you resolve the conflicts, please?

**Comment by varkor** [comment]
I've rebased and fixed the conflicts.

**Comment by ScyllaHide** [comment]
Is this now included in the new release, because I downloaded 0.60 and I can not find it?

**Comment by yishn** [comment]
This is not merged yet, so it‘s not in the official release yet. I‘m super busy atm and I don’t know when I‘ll have the time to look over this...

**Comment by varkor** [comment]
@yishn: have you had a chance to look at this more recently?

**Comment by yishn** [comment]
Thanks for the reminder! I've tested it out and it is lovely. ❤

**Comment by varkor** [comment]
@yishn: thank you very much, and thank you for developing tikzcd-editor — it's a really helpful and time-saving tool!

**Pull request merged**
