### PR TITLE
create reverse arrow button

### PR DESCRIPTION
**Pull request by rubenpieters**
creates a new button which reverses the direction of the arrow, it doesn't have an icon yet

### CODE REVIEW

**Comment by yishn** [comment]
I've added an icon. Do you think we should invert the label placement as well? Should the `bend` attribute be inverted?

**Comment by rubenpieters** [comment]
No problem. I guess inverting the `bend` attribute might be a good idea since that is more in line with what people would expect to happen.

**Comment by rubenpieters** [comment]
I added inversion of `labelPosition` and `bend`. I also added a default `labelPosition` of `'left'` since if not set it would give problems with the inversion.

**Comment by yishn** [comment]
Thank you very much!

**Pull request merged**
